# -*- coding: utf-8 -*-
"""Decimal_Hexadecimal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FaupWOxyqC-ENnNR1qQe7tHbuoSGsGVb

# Decimal to Hexadecimal
"""

# Decimal to Hexadecimal

# just in case if the user inputted is not a number
try:
  decimal = int(input("Input the decimal number: "))
  hexadecimal = ""
  all_hexadecimal_numbers = "0123456789ABCDEFG"

  # deviding the inputted number with 2 until it remains 0 and
  # store the remainder of the division in a variabel named "hexadecimal"
  while decimal is not 0:
    
    # translating the decimal to hexadecimal
    pre_hexadecimal = str(decimal%16)
    hexadecimal += all_hexadecimal_numbers[int(pre_hexadecimal)]
    decimal //= 16

  # reversing the number in variabel named "hexadecimal"
  final_hexadecimal = ""
  standard_number = -1

  for i in range(len(hexadecimal)):
    if i == 0:  # the condition when accessing the first number from the back
      operation_number = i + standard_number
      final_hexadecimal += hexadecimal[operation_number]
     
    else: # the rest
      operation_number = (i * standard_number)+(-1)
      final_hexadecimal += hexadecimal[operation_number]

  print(final_hexadecimal)

# a warn message for the user that the entered number is not a number
except ValueError:
  print("the inputted number is not a number")



"""# Hexadecimal to Decimal

"""

# Hexadecimal to Decimal

# just in case if the user inputted is not a number
hexadecimal = (str(input("Input the hexadecimal number: "))).upper()
is_hexadecimal = True
all_hexadecimal_numbers = "0123456789ABCDEF"

# to check if the entered number is a hexadecimal number
for i in str(hexadecimal):
  if i not in all_hexadecimal_numbers:
    is_hexadecimal = False
    break
    
# to process the conversion of hexadecimal number to decimal number
if is_hexadecimal == True:


  # translating the hexadecimal to decimal
  def get_the_index(hexadecimal_element):
    index = 0
    for i in all_hexadecimal_numbers:
      if i == hexadecimal_element:
        break

      else:
        index += 1

    return index


  pre_hexadecimal = []
  for i in hexadecimal:
    pre_hexadecimal.append(str(get_the_index(i)))

  # converting needs to read the hexadecimal numbers from back to front
  standard_number = len(pre_hexadecimal) - 1
  decimal = 0

  for i in pre_hexadecimal:
    decimal += int(i)*(16**standard_number)
    standard_number -= 1

  print(decimal)

# a warn message for the user that the entered number is not a hexadecimal number
else:
  print("the inputted number is not a hexadecimal number")