# -*- coding: utf-8 -*-
"""Decimal_Oktal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wkD21VOaNkBAq1AUYq-8-ok6b7l93UJT

# Decimal to Oktal
"""

# Decimal to Oktal

# just in case if the user inputted is not a number
try:
  decimal = int(input("Input the decimal number: "))
  oktal = ""

  # deviding the inputted number with 2 until it remains 0 and
  # store the remainder of the division in a variabel named "oktal"
  while decimal is not 0:
    oktal += str(decimal%8)
    decimal //= 8

  # reversing the number in variabel named "oktal"
  final_oktal = ""
  standard_number = -1

  for i in range(len(oktal)):
    if i == 0:  # the condition when accessing the first number from the back
      operation_number = i + standard_number
      final_oktal += oktal[operation_number]
     
    else: # the rest
      operation_number = (i * standard_number)+(-1)
      final_oktal += oktal[operation_number]

  print(final_oktal)

# a warn message for the user that the entered number is not a number
except ValueError:
  print("the inputted number is not a number")

"""# Oktal to Decimal"""

# OKtal to Decimal

# just in case if the user inputted is not a number
try:
  oktal = int(input("Input the oktal number: "))
  is_oktal = True
  all_oktal_numbers = "01234567"

  # to check if the entered number is a oktal number
  for i in str(oktal):
    if i not in all_oktal_numbers:
      is_oktal = False
      break
      

  # to process the conversion of oktal number to decimal number
  if is_oktal == True:
    standard_number = len(str(oktal)) - 1
    decimal = 0

    # converting needs to read the oktal numbers from back to front
    for i in str(oktal):
      decimal += int(i)*(8**standard_number)
      standard_number -= 1

    print(decimal)

  # a warn message for the user that the entered number is not a oktal number
  else:
    print("the inputted number is not a oktal number")

# a warn message for the user that the entered number is not a number
except ValueError:
  print("the inputted number is not a number")